# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadanie',
            name='polecenie',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
